######################################################################
# Automatically generated by qmake (3.0) ?? 9? 7 13:53:00 2018
######################################################################

TEMPLATE = app
TARGET = test-dbus-conf
INCLUDEPATH += .

QT -= gui
QT += dbus core

CONFIG += c++11

DBUS_ADAPTORS += cn.kosl90.dbus.Test.xml

# Input
SOURCES += main.cpp
HEADERS += DBusImpl.h
